/**
 * Sample Weekly Exercise Plans Generated by Workout Engine
 * These show what users will see when they request their weekly exercises
 */

// BEGINNER PLAN (3 days/week) - Full Body Focus
const beginnerWeeklyPlan = {
  name: 'Beginner Full Body',
  fitnessLevel: 'beginner',
  sessionsPerWeek: 3,
  totalExercises: 12,
  sessions: [
    {
      day: 1,
      name: 'Full Body A',
      dayOfWeek: 'Monday',
      exercises: [
        {
          name: 'Push-ups',
          sets: 3,
          reps: 10,
          rest: 60,
          difficulty: 'beginner',
          targetMuscles: ['chest', 'triceps', 'shoulders'],
          formGuidance: 'Keep body straight, lower chest to ground, push back up. Elbows at 45 degrees.',
          equipment: 'none'
        },
        {
          name: 'Barbell Rows',
          sets: 3,
          reps: 8,
          rest: 120,
          difficulty: 'beginner',
          targetMuscles: ['back', 'biceps'],
          formGuidance: 'Bend slightly, pull bar to chest, squeeze back muscles.',
          equipment: 'barbell'
        },
        {
          name: 'Leg Press',
          sets: 3,
          reps: 10,
          rest: 90,
          difficulty: 'beginner',
          targetMuscles: ['quadriceps', 'glutes'],
          formGuidance: 'Plant feet shoulder-width, press weight away, control descent.',
          equipment: 'machine'
        },
        {
          name: 'Planks',
          sets: 3,
          reps: 30,
          rest: 60,
          difficulty: 'beginner',
          targetMuscles: ['core', 'shoulders'],
          formGuidance: 'Keep body straight, engage core, don\'t let hips sag. Hold steady.',
          equipment: 'none'
        }
      ]
    },
    {
      day: 3,
      name: 'Full Body B',
      dayOfWeek: 'Wednesday',
      exercises: [
        {
          name: 'Lat Pulldown',
          sets: 3,
          reps: 10,
          rest: 90,
          difficulty: 'beginner',
          targetMuscles: ['back', 'biceps'],
          formGuidance: 'Pull bar down to chest, squeeze lats, control ascent.',
          equipment: 'cable machine'
        },
        {
          name: 'Dumbbell Bench Press',
          sets: 4,
          reps: 10,
          rest: 90,
          difficulty: 'intermediate',
          targetMuscles: ['chest', 'triceps', 'shoulders'],
          formGuidance: 'Press dumbbells up from chest level, control descent.',
          equipment: 'dumbbells'
        },
        {
          name: 'Leg Extensions',
          sets: 3,
          reps: 12,
          rest: 60,
          difficulty: 'beginner',
          targetMuscles: ['quadriceps'],
          formGuidance: 'Extend legs fully, squeeze quads, control descent.',
          equipment: 'machine'
        },
        {
          name: 'Dumbbell Lateral Raise',
          sets: 3,
          reps: 12,
          rest: 60,
          difficulty: 'beginner',
          targetMuscles: ['shoulders'],
          formGuidance: 'Raise dumbbells to shoulder height, slight bend in elbow.',
          equipment: 'dumbbells'
        }
      ]
    },
    {
      day: 5,
      name: 'Full Body C',
      dayOfWeek: 'Friday',
      exercises: [
        {
          name: 'Pull-ups',
          sets: 3,
          reps: 5,
          rest: 120,
          difficulty: 'beginner',
          targetMuscles: ['back', 'biceps'],
          formGuidance: 'Grip shoulder-width, pull body up, lower with control.',
          equipment: 'pull-up bar'
        },
        {
          name: 'Barbell Curl',
          sets: 3,
          reps: 10,
          rest: 60,
          difficulty: 'beginner',
          targetMuscles: ['biceps'],
          formGuidance: 'Keep elbows fixed, curl bar up, lower with control.',
          equipment: 'barbell'
        },
        {
          name: 'Leg Curls',
          sets: 3,
          reps: 12,
          rest: 60,
          difficulty: 'beginner',
          targetMuscles: ['hamstrings'],
          formGuidance: 'Curl legs up, squeeze at top, control descent. Full range of motion.',
          equipment: 'machine'
        },
        {
          name: 'Cable Crunches',
          sets: 3,
          reps: 12,
          rest: 60,
          difficulty: 'beginner',
          targetMuscles: ['abs'],
          formGuidance: 'Crunch forward, squeeze abs at bottom, control descent. Rope attachment.',
          equipment: 'cable machine'
        }
      ]
    }
  ]
};

// INTERMEDIATE PLAN (4 days/week) - Upper/Lower Split
const intermediateWeeklyPlan = {
  name: 'Upper/Lower Split',
  fitnessLevel: 'intermediate',
  sessionsPerWeek: 4,
  totalExercises: 16,
  sessions: [
    {
      day: 1,
      name: 'Upper Power',
      dayOfWeek: 'Monday',
      focus: 'Compound upper body strength',
      exercises: [
        'Barbell Bench Press (4x8, 120s rest)',
        'Barbell Rows (4x8, 120s rest)',
        'Overhead Press (3x8, 120s rest)',
        'Barbell Curl (3x10, 60s rest)'
      ]
    },
    {
      day: 2,
      name: 'Lower Power',
      dayOfWeek: 'Tuesday',
      focus: 'Compound lower body strength',
      exercises: [
        'Squats (4x8, 150s rest)',
        'Romanian Deadlifts (3x8, 120s rest)',
        'Leg Press (3x10, 90s rest)',
        'Cable Crunches (3x12, 60s rest)'
      ]
    },
    {
      day: 4,
      name: 'Upper Hypertrophy',
      dayOfWeek: 'Thursday',
      focus: 'Upper body muscle growth',
      exercises: [
        'Dumbbell Bench Press (4x10, 90s rest)',
        'Lat Pulldown (4x10, 90s rest)',
        'Dumbbell Lateral Raise (3x12, 60s rest)',
        'Tricep Dips (3x10, 90s rest)'
      ]
    },
    {
      day: 5,
      name: 'Lower Hypertrophy',
      dayOfWeek: 'Friday',
      focus: 'Lower body muscle growth',
      exercises: [
        'Leg Extensions (4x12, 60s rest)',
        'Leg Curls (4x12, 60s rest)',
        'Dumbbell Lateral Raise (3x12, 60s rest)',
        'Planks (3x30s, 60s rest)'
      ]
    }
  ]
};

// ADVANCED PLAN (5 days/week) - Push/Pull/Legs
const advancedWeeklyPlan = {
  name: 'Push/Pull/Legs',
  fitnessLevel: 'advanced',
  sessionsPerWeek: 5,
  totalExercises: 21,
  sessions: [
    {
      day: 1,
      name: 'Push (Chest/Shoulders/Triceps)',
      dayOfWeek: 'Monday',
      focus: 'Upper body pressing - maximum volume',
      exercises: [
        'Barbell Bench Press (4x8, 120s rest)',
        'Overhead Press (4x8, 120s rest)',
        'Dumbbell Bench Press (3x10, 90s rest)',
        'Dumbbell Lateral Raise (3x12, 60s rest)',
        'Tricep Dips (3x10, 90s rest)'
      ]
    },
    {
      day: 2,
      name: 'Pull (Back/Biceps)',
      dayOfWeek: 'Tuesday',
      focus: 'Upper body pulling - maximum volume',
      exercises: [
        'Deadlifts (4x6, 180s rest)',
        'Barbell Rows (4x8, 120s rest)',
        'Pull-ups (4x6, 120s rest)',
        'Lat Pulldown (3x10, 90s rest)',
        'Barbell Curl (3x10, 60s rest)'
      ]
    },
    {
      day: 3,
      name: 'Legs',
      dayOfWeek: 'Wednesday',
      focus: 'Lower body - maximum strength and volume',
      exercises: [
        'Squats (4x8, 150s rest)',
        'Romanian Deadlifts (3x8, 120s rest)',
        'Leg Extensions (3x12, 60s rest)',
        'Leg Curls (3x12, 60s rest)',
        'Cable Crunches (3x12, 60s rest)'
      ]
    },
    {
      day: 4,
      name: 'Push (Accessory)',
      dayOfWeek: 'Friday',
      focus: 'Upper body pressing - high volume accessories',
      exercises: [
        'Dumbbell Bench Press (4x10, 90s rest)',
        'Dumbbell Lateral Raise (4x12, 60s rest)',
        'Barbell Curl (3x10, 60s rest)',
        'Tricep Dips (3x12, 90s rest)',
        'Planks (3x45s, 60s rest)'
      ]
    },
    {
      day: 5,
      name: 'Pull (Accessory)',
      dayOfWeek: 'Saturday',
      focus: 'Upper body pulling - high volume accessories',
      exercises: [
        'Lat Pulldown (4x10, 90s rest)',
        'Barbell Rows (3x10, 120s rest)',
        'Pull-ups (3x8, 120s rest)',
        'Cable Crunches (3x12, 60s rest)'
      ]
    }
  ]
};

export {
  beginnerWeeklyPlan,
  intermediateWeeklyPlan,
  advancedWeeklyPlan
};
